### ISSUE TITLE
AttributeError: 'Quart' object has no attribute 'discord_client_session'

### ISSUE THREAD

**Issue by cgeopapa** [Breq16/flask-discord-interactions#59]
Trying to create an async command with Quart ends up in this error message. Here is my code:

```python
import asyncio
import quart.flask_patch
from quart import Quart
from flask_discord_interactions import DiscordInteractions, Message

app = Quart(__name__)
discord = DiscordInteractions(app)

load_dotenv()

app.config["DISCORD_CLIENT_ID"] = os.getenv("DISCORD_CLIENT_ID")
app.config["DISCORD_PUBLIC_KEY"] = os.getenv("DISCORD_PUBLIC_KEY")
app.config["DISCORD_CLIENT_SECRET"] = os.getenv("DISCORD_CLIENT_SECRET")
PORT = int(os.environ.get("PORT", 5000))

@discord.command()
async def wake(ctx):
    "Wake the bot up. Not necessary but very kind indeed."
    await asyncio.sleep(1)
    return "I'm awake"

discord.set_route("/interactions")
discord.update_commands(guild_id=os.getenv("TEST_SERVER_ID"))


if __name__ == '__main__':
    app.run(port=PORT)
```

And here is all of the stack trace:
```
[2021-11-17 17:56:39,313] ERROR in app: Exception on request POST /interactions
Traceback (most recent call last):
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\quart\app.py", line 1488, in handle_request
    return await self.full_dispatch_request(request_context)
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\quart\flask_patch\app.py", line 27, in new_full_dispatch_request
    return await old_full_dispatch_request(self, request_context)
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\quart\app.py", line 1513, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\quart\app.py", line 963, in handle_user_exception
    raise error
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\quart\app.py", line 1511, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\quart\app.py", line 1556, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\quart\flask_patch\app.py", line 43, in _wrapper
    result = func(*args, **kwargs)
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\flask_discord_interactions\discord.py", line 514, in interactions
    return jsonify(self.run_command(request.json).dump())
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\flask_discord_interactions\discord.py", line 434, in run_command
    return command.make_context_and_run(self, current_app, data)
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\flask_discord_interactions\command.py", line 172, in make_context_and_run
    context = AsyncContext.from_data(discord, app, data)
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\flask_discord_interactions\context.py", line 89, in from_data
    result = cls(
  File "<string>", line 24, in __init__
  File "F:\Projects\minecraft-server-bot-v3\venv\lib\site-packages\flask_discord_interactions\context.py", line 432, in __post_init__
    self.session = self.app.discord_client_session
AttributeError: 'Quart' object has no attribute 'discord_client_session'
```

**Comment by Breq16** [comment]
If you're using Quart with async functions, you need to use `discord.set_route_async` instead of `discord.set_route`.

Replace
```python
discord.set_route("/interactions")
```
with
```python
discord.set_route_async("/interactions")
```

**Comment by cgeopapa** [comment]
Oh ok now it works, thank you! This should be mentioned in the docs.

**Comment by Breq16** [comment]
Agreed--this was an oversight on my part. Thanks for filing an issue!
